name: Production deployment
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [v20.9.0]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Configure environment variables
        run: |
          echo -e "NEXT_PUBLIC_GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_API_URL }}\nNEXT_PUBLIC_ENVIRONMENT=production\nENABLE_SITEMAP=true\nNEXT_PUBLIC_BASE_URL=https://expenses.makerdao.network\nNEXT_PUBLIC_GA_TRACKING_ID=${{ secrets.GA_TRACKING_ID }}\nNEXT_PUBLIC_CONNECT=${{ secrets.NEXT_PUBLIC_CONNECT }}\n" >> .env
      - name: Install project
        run: |
          npm install -g yarn
          yarn
          yarn build
      - name: Copy file via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_PRODUCTION }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASS_PRODUCTION }}
          source: "./"
          target: "/var/www/next/app-production-tmp"
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST_PRODUCTION }}
          USERNAME: ${{ secrets.SSH_USER_PRODUCTION }}
          PORT: ${{ secrets.SSH_PORT }}
          PASSWORD: ${{ secrets.SSH_PASS_PRODUCTION }}
          script: |
            pm2 stop next-js-production
            mv /var/www/next/app-production /var/www/next/app-production-del
            mv /var/www/next/app-production-tmp /var/www/next/app-production
            pm2 start next-js-production
            rm -rf /var/www/next/app-production-del
