name: Validating PR
on:
  pull_request:
    branches:
      - master
jobs:
  validate-pr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ v16.x ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Install project
        run: |
          npm install -g yarn
          yarn
      - name: Configure environment variables
        run: |
          echo -e "NEXT_PUBLIC_ENVIRONMENT=development" >> .env
      - name: Validate
        run: |
          yarn run eslint src/**/*{.ts,.tsx}
          yarn jest 
          yarn build
        env:
          CI: true
